server:
  port: 8080
  servlet:
    context-path: /kmajourney


spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3308/kmajourney"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: vanphuctruggc@gmail.com
    password: dmei ekwu fipn qrnk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
