server:
  port: 8080
  servlet:
    context-path: /kmajourney
jwt:
  signerKey: "${SIGNER_KEY}"
  VALID_DURATION: 3600
  REFRESHABLE_DURATION: 86400
spring:
  datasource:
    url: "${DATASOURCE_URL}"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: vanphuctruggc@gmail.com
    password: dmei ekwu fipn qrnk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
